version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Installing libraries
          command: |
            python3 -m venv venv
            . venv/bin/activate
      - run:
          name: Installing aws-command-line
          command: sudo pip install awscli

      - run:
          name: Validate
          command: pwd

      - run:
          name: Zip Artifact
          command: |
            zip index.zip index.js

      - run:
          name: Upload the zip of lambda to S3 Bucket
          command: |
            aws s3 cp index.zip s3://${S3_BUCKET_ADDR}/index.zip
      
      - run:
          name: Update lambdaFunction code
          command: |
            aws lambda update-function-code --function-name forgotpasswordResetlambda --region us-east-1 --zip-file fileb://index.zip